edition: 1.0.0
name: video-insight-app
access: default

services:
  video-insight:
    component: fc
    props:
      region: cn-hangzhou
      service:
        name: video-insight
        description: "Video Insight Feishu Bot"
        internetAccess: true
      function:
        name: bot-processor
        description: "Process video analysis tasks"
        runtime: custom-container
        caPort: 9000
        memorySize: 4096
        timeout: 900
        customContainerConfig:
          image: "registry.cn-hangzhou.aliyuncs.com/YOUR_NAMESPACE/video-insight:latest"
        environmentVariables:
          FEISHU_APP_ID: ${env(FEISHU_APP_ID)}
          FEISHU_APP_SECRET: ${env(FEISHU_APP_SECRET)}
          FEISHU_VERIFICATION_TOKEN: ${env(FEISHU_VERIFICATION_TOKEN)}
          FEISHU_ENCRYPT_KEY: ${env(FEISHU_ENCRYPT_KEY)}
          FEISHU_FOLDER_TOKEN: "Vu7IfSC4iluS4KdgsSfctge8nAG"
          DASHSCOPE_API_KEY: ${env(DASHSCOPE_API_KEY)}
          TEMP_CLEANUP_ENABLED: "true"
      triggers:
        - name: http-trigger
          type: http
          config:
            authType: anonymous
            methods:
              - POST
